# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [ ]:
p = 2.0 + 3.0 / 5.0 == 10
print(p)
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
print(q)
r = 10 <= p / q + 33.8 < 100
print(r)
s = 5!= p /  (q+r)
print(s)
t = 33 == s * 2
print(t)
result = p or r and s or t
print('Para modificar o resultado basta modificar as comparações entre p e r para or e as comparações entre o resultado e t já que somente p e t são False, portanto havendo um valor verdadeiro tudo será verdadeiro ', result)

False
True
True
True
False
True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [ ]:
import pandas as pd
df = pd.read_csv('../storage/aula_005.csv', index_col=0).round(3)
segunda_linha = df.iloc[1]
terceira_linha = df.iloc[2]
quarta_linha = df.iloc[3]
resultado = (segunda_linha is terceira_linha) or (terceira_linha is quarta_linha)
print("O resultado da condição é:", resultado)

col_2          1.612
col_3          1.673
col_4          5.893
media_linha    2.329
Name: 0.139, dtype: float64
col_2          0.372
col_3          2.600
col_4          2.800
media_linha    1.509
Name: 0.263, dtype: float64
col_2          0.069
col_3          0.139
col_4          1.612
media_linha    9.137
Name: 34.729, dtype: float64
O resultado da condição é: False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [7]:
primeira_linha = df.iloc[0]
print(primeira_linha)
resultado = (primeira_linha >= 10).all()

print("Todos os valores da primeira linha são >= 10?", resultado)

col_2           2.800
col_3          34.729
col_4           0.069
media_linha    10.050
Name: 2.6, dtype: float64
Todos os valores da primeira linha são >= 10? False

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [11]:
terceira_coluna = df.iloc[:, 2]
resultado = ((terceira_coluna >= 0) & (terceira_coluna <= 40)).all()
print("Os valores da terceira coluna estão entre 0 e 40?", resultado)

Os valores da terceira coluna estão entre 0 e 40? True

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [14]:
ultima_linha = df.iloc[-1]
result = (ultima_linha > 10).any()
result

np.False_

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [ ]:
result = df[((df > 5) & (df < 7))]
result

        col_2  col_3  col_4  media_linha
col_1
2.600     NaN    NaN    NaN          NaN
0.139     NaN    NaN  5.893          NaN
0.263     NaN    NaN    NaN          NaN
34.729    NaN    NaN    NaN          NaN
1.673   5.893    NaN    NaN          NaN
7.881     NaN    NaN    NaN        5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [21]:
result = df[((df < 5) | (df >= 7))]
result

        col_2   col_3  col_4  media_linha
col_1
2.600   2.800  34.729  0.069       10.050
0.139   1.612   1.673    NaN        2.329
0.263   0.372   2.600  2.800        1.509
34.729  0.069   0.139  1.612        9.137
1.673     NaN   0.263  0.372        2.050
7.881   2.149   7.881  2.149          NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [27]:
print(df)
duas_ultimas_colunas = df.iloc[:, -2:]
array_1 = duas_ultimas_colunas.iloc[:, 0].to_numpy()
print(array_1)
array_2 = duas_ultimas_colunas.iloc[:, 1].to_numpy()
result = ((array_1 >= 2) & (array_1 <= 5)).any()
print("Algum valor do primeiro array está entre 2 e 5?", result)

        col_2   col_3  col_4  media_linha
col_1
2.600   2.800  34.729  0.069       10.050
0.139   1.612   1.673  5.893        2.329
0.263   0.372   2.600  2.800        1.509
34.729  0.069   0.139  1.612        9.137
1.673   5.893   0.263  0.372        2.050
7.881   2.149   7.881  2.149        5.015
[0.069 5.893 2.8   1.612 0.372 2.149]
Algum valor do primeiro array está entre 2 e 5? True

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [ ]:
primeiro_array_condicao = ((array_1 > -1) & (array_1 < 12))
segundo_array_condicao = ((array_2 > -1) & (array_2 < 12))
result = (primeiro_array_condicao & segundo_array_condicao).all()
print("Todos os valores dos arrays está estão -1 e 12 ?", result)